<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "kuehnleintemplate"
 *
 * Auto generated by Extension Builder 2017-06-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'kuehnlein-template',
    'description' => 'Template für Kühnlein',
    'category' => 'templates',
    'author' => 'Pascale Beier',
    'author_email' => 'p.beier@ruhr-connect.de',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '2017.07.13',
    'constraints' => [
        'depends' => [
            'vhs' => '4.0.0-4.99.99',
            'typo3' => '8.6.0-8.99.99',
            'realurl' => '2.0.0-2.99.99'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
